# Embedded Server
server:
  port: 8002

# Cloud Bus
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123qweasd

# This controls which Actuator web endpoints are exposed.
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,bus-refresh